### ISSUE TITLE
Password in Options not used correctly

### ISSUE THREAD

**Issue by ChrisNbg** [bkbartk/mRemoteNG-develop#13]
Hi,
I used mRemoteNG and imported the config in dRemote. Works good so far. But in most connections there is no username and no password.
I used the possability of the default password in the options (with a few special characters like # or \ aso.)
User and Domain are caught correctly but there seems to be an issue with the password. It says always "the logon failed" and ask for a password. I copied it to clipboard and paste it in the options and paste it into the password-dialog. 

I think the password is going to be destroyed during saving.

**Comment by bkbartk** [comment]
Hi Christian,
thank you for the bugreport.
I will investigate this issue as soon as possible, probably this evening.
I have improved the encryption in dRemote, and I missed this option while converting the old passwords into the new once. 
What you could do is of course make a backup of your configuration file and then try to set your credentials again.

I'm really sorry for the inconvenience, this shouldn't have happened.

**Comment by ChrisNbg** [comment]
Thankyou for you quick reply. 
I like your work very much. works better than mRemoteNG and the mRemote3G fork especially with a lot of parallel connections to 2012R2-machines.

I found the config file under C:\Users\xxx\AppData\Local\dRemote\dRemote.exe_Url_grfzdo1es2yvowcvr1gxshrjhahjnq5q\0.3.8.0\user.config and tried to paste the encypted password from the confCons.xml but it didn't work.

When I put the cedentials directly to the connection everything is fine...

**Comment by bkbartk** [comment]
Hi Christian,

I've created a fix for this issue and published it.
You might have to save your settings one more time. The issue was that the password was encrypted the new way but while reading the value, it tried to use the old way of encryption.

sorry for the inconvenience. would you please let me know if the fix also works for you? 

Thank you.

**Comment by ChrisNbg** [comment]
Your Fix works! Thank you. :+1:
