### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by bveldkamp** [bkbartk/mRemoteNG-develop#6]
At startup, I get an error message (roughly translated from Dutch): 

```
Error on Webpage
================
Line: 2
Error: The property or method addEventListener is not supported by this object
```

![clipboard](https://cloud.githubusercontent.com/assets/7160755/13978913/f4687cc4-f0d4-11e5-800d-f26873547a29.png)

And then:

```
Scripting error
===============
An error occured in the script on this page
Would you like to continue executing scripts on this page? [Yes] [No]
```

![clipboard_1](https://cloud.githubusercontent.com/assets/7160755/13978930/1132cd5a-f0d5-11e5-860b-1e27485f78a9.png)

My dRemote version is 0.2.213.0

**Comment by bkbartk** [comment]
thank you for reporting,
I cannot reproduce this error, However I have made a fix which should disable this message
this will be available after the next release.
