### ISSUE TITLE
Exception when opening a connection

### ISSUE THREAD

**Issue by bveldkamp** [bkbartk/mRemoteNG-develop#7]
I imported a mRemote connection file. Now, when I doubleclick a (rdp) connection, I get this message:

```
An unexpected exception occurred in the application. If you 
click Continue, the error will be ignored and the application will 
continue.. If you click Close the application will be closed immediately.
```

I included the stacktrace below.

![clipboard_2](https://cloud.githubusercontent.com/assets/7160755/13979047/f31f220e-f0d5-11e5-83e8-3913ad0ad8ec.png)
[Stacktrace.txt](https://github.com/bkbartk/dRemote/files/185563/Stacktrace.txt)

dRemote: 0.2.213.0

**Comment by bkbartk** [comment]
unfortunately I'm unable to reproduce this item, If you have any more information please share it with me.

**Comment by bveldkamp** [comment]
It works on another machine, I'll have to get back on this next week when I'm back in the other office.

**Comment by bveldkamp** [comment]
Looking at the sources, I see there are some dependencies on COM libraries. Could it be I need to register those? I'm using the portable version now.

**Comment by strikegun** [comment]
I got the same problem when I try a RDP connection.
SSH or Telnet works.
Tried installer and portable. both the same.

**Comment by bkbartk** [comment]
Can you please tell me which windows version you are using and if this is 32 of 64 bit so I can investigate this further?

**Comment by bveldkamp** [comment]
Windows 7 Enterprise 64 bits

**Comment by bkbartk** [comment]
thank you for the answer,
I will setup a testenvironment running
Windows 7 Enterprise 64 bits dutch
without any service packs to check out if I can reproduce the issue

**Comment by bkbartk** [comment]
Let me do a small update,
the good news is that I was able to reproduce the issue using the portable version.
the bad news is that windows 7 without SP1 has conflicts with my network card
tomorrow I will try if my network card works better with SP 1 and if the issue then also occurs.

**Comment by bkbartk** [comment]
It took me a while but I was able to fix this issue.
It will be available in the next release.
probably somewhere in the beginning of next week.
